Repository schote/nexus-console, pull requests merged in 2025-07, with the labels that each got.

#102 Gradient delay fixed
  src/console/pulseq_interpreter/sequence_provider.py
Labels: priority: critical, type: bug

#100 Error handling when loading state file
  src/console/__init__.py
  src/console/interfaces/acquisition_parameter.py
Labels: priority: high, type: fix

#110 Adds automatic versioning to nexus-console project
  .github/workflows/deploy.yml
  .github/workflows/docs.yml
  .github/workflows/gitlab-push.yml
  .github/workflows/pytest.yml
  .github/workflows/static-tests.yml
  docs/source/conf.py
  pyproject.toml
  src/console/_version.py
  src/console/py.typed
Labels: priority: medium

#111 Fix deployment
  .github/workflows/deploy.yml
Labels: priority: high, type: fix

#117 Updated/fixed versioning
  .github/workflows/deploy.yml
  .github/workflows/deployment.yml
  .github/workflows/docs.yml
  .github/workflows/pytest.yml
  .github/workflows/static-tests.yml
  pyproject.toml
  src/console/_version.py
Labels: priority: high, type: fix, type: improvement
